---
channel: stable
addons:
  snapmaker-monitor:
    repository: NRE-Com-Net/hassio-addon-snapmaker-monitor
    target: snapmaker-monitor
    image: ghcr.io/NRE-Com-Net/hassio-addon-snapmaker-monitor/{arch}
